apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkc-app2
spec:
  distribution:
    version: v1.18
  topology:
    controlPlane:
      class: best-effort-small
      count: 1
      storageClass: tanzu-basic-storage-policy
    workers:
      class: best-effort-small
      count: 1
      storageClass: tanzu-basic-storage-policy 
  settings:
    storage:
      classes: ["tanzu-basic-storage-policy"]
      defaultClass: tanzu-basic-storage-policy 
