apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkc-app-cl1
  namespace: ns-tools
spec:
  distribution:
    version: v1.19
  topology:
    controlPlane:
      class: best-effort-small
      count: 1
      storageClass: tanzu-basic-storage-policy
    workers:
      class: best-effort-small
      count: 2
      storageClass: tanzu-basic-storage-policy
  settings:
    network:
      cni:
        name: antrea 
      pods:
        cidrBlocks: ["10.55.0.0/16"]
    storage:
      classes: ["tanzu-basic-storage-policy"]
      defaultClass: tanzu-basic-storage-policy
